# Generated by Django 6.0.5 on 2026-05-14 06:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_skill_profile_skill_user_user_avatar_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
